environment:
  matrix:
    - nodejs_version: "0.11"
    - nodejs_version: "0.12"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - choco install gow

test_script:
  - npm test

build: off
